In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
dataset = pd.read_csv("C:\\Users\\Prakhar Agrawal\\Downloads\\newmovies.csv")

In [5]:
dataset.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [6]:
dataset.shape


(4803, 24)

In [7]:
main_features = ['genres' , 'keywords' , 'original_title' ,'overview' ,'tagline' , 'cast' , 'director']

In [8]:
print(main_features)

['genres', 'keywords', 'original_title', 'overview', 'tagline', 'cast', 'director']


In [9]:
for i in main_features:
    dataset[i] = dataset[i].fillna(' ')

In [10]:
combined_features = dataset['genres']+' ' + dataset['keywords']+' ' + dataset['original_title']+' ' + dataset['overview']+' ' + dataset['tagline']+' ' + dataset['cast']+' ' + dataset['director']

In [11]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance   Newlyweds A newlywed couple's...
4800    Comedy Drama Romance TV Movie date love at fir...
4801        Shanghai Calling When ambitious New York a...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [12]:
vectorizer = TfidfVectorizer()

In [13]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [14]:
print(feature_vectors)

  (0, 4426)	0.13004959062649668
  (0, 14613)	0.08285434427286248
  (0, 23831)	0.14751739050825702
  (0, 18308)	0.1209228707427199
  (0, 16039)	0.16866690346528304
  (0, 26651)	0.11408262788981283
  (0, 30530)	0.14827639152021851
  (0, 25547)	0.1564219964497782
  (0, 24283)	0.16537327333542137
  (0, 31484)	0.14827639152021851
  (0, 31077)	0.17956496748351683
  (0, 24326)	0.10873330498132479
  (0, 19995)	0.03086073726102991
  (0, 31052)	0.0710720050721456
  (0, 9335)	0.1404215434342093
  (0, 5419)	0.162468085668314
  (0, 1041)	0.12041947395189906
  (0, 1278)	0.05170708949059431
  (0, 22177)	0.16387793147534246
  (0, 1318)	0.03128010560257728
  (0, 20243)	0.1586658687241279
  (0, 10681)	0.13630105644048626
  (0, 3074)	0.09806903974305067
  (0, 28357)	0.14277242492893585
  (0, 2776)	0.09641431696741483
  :	:
  (4802, 19815)	0.05838586925209494
  (4802, 12303)	0.07491587425479584
  (4802, 30597)	0.07401988990893983
  (4802, 9624)	0.06749774524446993
  (4802, 20070)	0.0548813572618499
  (480

In [15]:
similarity = cosine_similarity(feature_vectors)

In [16]:
similarity.shape

(4803, 4803)

In [17]:
print(similarity)

[[1.         0.0540225  0.03084845 ... 0.02436576 0.02810208 0.00666179]
 [0.0540225  1.         0.04099378 ... 0.05361211 0.03669106 0.01553442]
 [0.03084845 0.04099378 1.         ... 0.0227109  0.0425595  0.01229387]
 ...
 [0.02436576 0.05361211 0.0227109  ... 1.         0.02988327 0.03921517]
 [0.02810208 0.03669106 0.0425595  ... 0.02988327 1.         0.02879873]
 [0.00666179 0.01553442 0.01229387 ... 0.03921517 0.02879873 1.        ]]


In [35]:
movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name : iron man


In [36]:
title_list = dataset['title'].tolist()

In [37]:
print(title_list)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [38]:
close_match = difflib.get_close_matches(movie_name, title_list)

In [39]:
print(close_match)

['Iron Man', 'Iron Man 3', 'Iron Man 2']


In [40]:
closest = close_match[0]

In [41]:
print(closest)

Iron Man


In [42]:
index = dataset[dataset.title==closest]['index'].values[0]

In [43]:
print(index)

68


In [44]:
similarity_score = list(enumerate(similarity[index]))
print(similarity_score)

[(0, 0.04857538612695869), (1, 0.03440222328859465), (2, 0.010299005574060025), (3, 0.006223718794364147), (4, 0.024878039428573216), (5, 0.0259134173536274), (6, 0.03206715761581329), (7, 0.1762577119155641), (8, 0.00914653141559054), (9, 0.03410308246218259), (10, 0.04042462411249284), (11, 0.012768813212243596), (12, 0.01579271789137606), (13, 0.009947705189289429), (14, 0.07131434188707067), (15, 0.026355219888050778), (16, 0.12797476172065197), (17, 0.015573235374047423), (18, 0.020892617158201912), (19, 0.04109838496904344), (20, 0.04164390554477197), (21, 0.027154391744513756), (22, 0.008754272751491016), (23, 0.015823780494792036), (24, 0.016910072928670684), (25, 0.003307904751372854), (26, 0.13437766806924337), (27, 0.032204892135374245), (28, 0.0344013721975263), (29, 0.009283199331374288), (30, 0.08412824050272563), (31, 0.3149900955336315), (32, 0.02481108570006163), (33, 0.07308538460422613), (34, 0.00525761226702995), (35, 0.019829758082645442), (36, 0.02359049581071516)

In [45]:
len(similarity_score)

4803

In [46]:
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_movies)

[(68, 1.0000000000000002), (79, 0.3678469396080506), (31, 0.3149900955336315), (7, 0.1762577119155641), (26, 0.13437766806924337), (16, 0.12797476172065197), (511, 0.11412261672327625), (182, 0.11049786206461995), (64, 0.10485431170291576), (3623, 0.10188380438699914), (94, 0.09616028131512831), (4033, 0.08451639234651681), (30, 0.08412824050272563), (618, 0.08252870519263858), (46, 0.08167082892725411), (174, 0.08057216862139531), (783, 0.08038379832141009), (3133, 0.07711905870573094), (101, 0.07692442508881309), (85, 0.07663744321639646), (203, 0.07512933953125649), (2875, 0.07506308450512694), (198, 0.07445619390187416), (3466, 0.07435250809645393), (1740, 0.07427648409946956), (131, 0.07349041489217954), (33, 0.07308538460422613), (318, 0.0716664382955606), (1177, 0.07163528375722014), (725, 0.07154639915632545), (2229, 0.07151137807110719), (14, 0.07131434188707067), (1406, 0.07072533060112163), (788, 0.07056610514429168), (1135, 0.07024260090652394), (169, 0.0702340399476245), (

In [47]:
print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = dataset[dataset.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . Iron Man
2 . Iron Man 2
3 . Iron Man 3
4 . Avengers: Age of Ultron
5 . Captain America: Civil War
6 . The Avengers
7 . X-Men
8 . Ant-Man
9 . X-Men: Apocalypse
10 . Made
11 . Guardians of the Galaxy
12 . Super
13 . Spider-Man 2
14 . Mystery Men
15 . X-Men: Days of Future Past
16 . The Incredible Hulk
17 . Mortdecai
18 . The Devil's Tomb
19 . X-Men: First Class
20 . Captain America: The Winter Soldier
21 . X2
22 . Two Lovers
23 . R.I.P.D.
24 . Sliding Doors
25 . Kick-Ass 2
26 . G-Force
27 . X-Men: The Last Stand
28 . Surf's Up
29 . Sin City


In [34]:
movie_name = input(' Enter your favourite movie name : ')

title_list = dataset['title'].tolist()

close_match = difflib.get_close_matches(movie_name, title_list)

closest = close_match[0]

index = dataset[dataset.title == closest]['index'].values[0]

similarity_score = list(enumerate(similarity[index]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = dataset[dataset.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name : avengers
Movies suggested for you : 

1 . The Avengers
2 . Avengers: Age of Ultron
3 . Captain America: The Winter Soldier
4 . Captain America: Civil War
5 . Iron Man 2
6 . X-Men
7 . The Incredible Hulk
8 . Thor: The Dark World
9 . X-Men: Apocalypse
10 . Captain America: The First Avenger
11 . Iron Man 3
12 . X-Men: Days of Future Past
13 . Ant-Man
14 . X-Men: The Last Stand
15 . Iron Man
16 . X-Men: First Class
17 . X2
18 . Man of Steel
19 . Thor
20 . The Amazing Spider-Man 2
21 . Guardians of the Galaxy
22 . Superman II
23 . The Shadow
24 . The Losers
25 . Serenity
26 . The Spirit
27 . The Horse Whisperer
28 . Fantastic 4: Rise of the Silver Surfer
29 . Kick-Ass
